// <auto-generated />
using System;
using EmployeeManagementPlatform.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementPlatform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928231232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("EmployeeManagementPlatform.Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Department");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "sarah.connor@example.com",
                            FirstName = "Sarah",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Connor",
                            Position = "VP of Engineering",
                            Salary = 95000m
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "alex.rivera@example.com",
                            FirstName = "Alex",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rivera",
                            Position = "Senior Full-Stack Developer",
                            Salary = 78000m
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Product",
                            Email = "elena.rostova@example.com",
                            FirstName = "Elena",
                            HireDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rostova",
                            Position = "Lead Product Manager",
                            Salary = 82000m
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Design",
                            Email = "marcus.vance@example.com",
                            FirstName = "Marcus",
                            HireDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Vance",
                            Position = "UI/UX Designer",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Human Resources",
                            Email = "amina.diallo@example.com",
                            FirstName = "Amina",
                            HireDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Diallo",
                            Position = "HR Director",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "david.kim@example.com",
                            FirstName = "David",
                            HireDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kim",
                            Position = "DevOps Engineer",
                            Salary = 74000m
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Email = "sofia.martins@example.com",
                            FirstName = "Sofia",
                            HireDate = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Martins",
                            Position = "Financial Analyst",
                            Salary = 62000m
                        },
                        new
                        {
                            Id = 8,
                            Active = false,
                            CreatedAt = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Email = "liam.chen@example.com",
                            FirstName = "Liam",
                            HireDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Chen",
                            Position = "Operations Specialist",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            HireDate = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Taylor",
                            Position = "Marketing Manager",
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "james.wilson@example.com",
                            FirstName = "James",
                            HireDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Wilson",
                            Position = "QA Automation Engineer",
                            Salary = 63000m
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "lucia.gomez@example.com",
                            FirstName = "Lucia",
                            HireDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Gomez",
                            Position = "Backend Developer",
                            Salary = 71000m
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Email = "ethan.hunt@example.com",
                            FirstName = "Ethan",
                            HireDate = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Hunt",
                            Position = "Security Specialist",
                            Salary = 80000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
